package doctor

// BuiltinDefinitions registers only providers implemented in the current stage.
func BuiltinDefinitions() []Definition {
	return []Definition{
		{Integration: Integration{ID: "pi", Name: "Pi", Description: "Coding agent installations in the selected environment.", References: []string{"https://github.com/earendil-works/pi"}, SupportedScopes: []string{"user"}}, Discover: discoverPi, Checks: []CheckDefinition{{ID: "pi", Name: "Pi version", Question: "Is a supported update available?", Order: 1, Evaluate: checkPiInstance}}},
		{Integration: Integration{ID: "herdr", Name: "Herdr", Description: "Terminal runtime installations and update sources.", References: []string{"https://github.com/herdrdev/herdr"}, SupportedScopes: []string{"user"}}, Discover: discoverHerdr, Checks: []CheckDefinition{{ID: "herdr", Name: "Herdr version", Question: "Is a supported update available?", Order: 2, Evaluate: checkHerdrInstance}}},
		{Integration: Integration{ID: "ghostty", Name: "Ghostty", Description: "Terminal application and command-line candidates.", References: []string{"https://ghostty.org/docs/install/binary"}, SupportedScopes: []string{"user"}}, Discover: discoverGhostty, Checks: []CheckDefinition{{ID: "ghostty", Name: "Ghostty version", Question: "Is a supported update available?", Order: 3, Evaluate: checkGhosttyInstance}}},
		{Integration: Integration{ID: "starship", Name: "Starship", Description: "Shell prompt installations and update sources.", References: []string{"https://github.com/starship/starship"}, SupportedScopes: []string{"user"}}, Discover: discoverStarship, Checks: []CheckDefinition{{ID: "starship", Name: "Starship version", Question: "Is a supported update available?", Order: 4, Evaluate: checkStarshipInstance}}},
		{Integration: Integration{ID: "opencode", Name: "OpenCode", Description: "OpenCode installations and evidenced update sources.", References: []string{"https://github.com/anomalyco/opencode"}, SupportedScopes: []string{"user"}}, Discover: discoverOpenCode, Checks: []CheckDefinition{{ID: "opencode", Name: "OpenCode version", Question: "Is a supported update available?", Order: 5, Evaluate: checkOpenCodeInstance}}},
		{Integration: Integration{ID: "tokenjuice", Name: "Tokenjuice", Description: "Output compactor installations and evidenced update sources.", References: []string{"https://github.com/vincentkoc/tokenjuice"}, SupportedScopes: []string{"user"}}, Discover: discoverTokenjuice, Checks: []CheckDefinition{{ID: "tokenjuice", Name: "Tokenjuice version", Question: "Is a supported update available?", Order: 6, Evaluate: checkTokenjuiceInstance}}},
	}
}
