package doctor

// BuiltinDefinitions registers only providers implemented in the current stage.
func BuiltinDefinitions() []Definition {
	defs := []Definition{
		{Integration: Integration{ID: "pi", Name: "Pi", Description: "Coding agent installations in the selected environment.", References: []string{"https://github.com/earendil-works/pi"}, SupportedScopes: []string{"user"}}, Discover: discoverPi, Checks: []CheckDefinition{{ID: "pi", Name: "Pi version", Question: "Is a supported update available?", Order: 1, Evaluate: checkPiInstance}}},
		{Integration: Integration{ID: "herdr", Name: "Herdr", Description: "Terminal runtime installations and update sources.", References: []string{"https://github.com/herdrdev/herdr"}, SupportedScopes: []string{"user"}}, Discover: discoverHerdr, Checks: []CheckDefinition{{ID: "herdr", Name: "Herdr version", Question: "Is a supported update available?", Order: 2, Evaluate: checkHerdrInstance}}},
		{Integration: Integration{ID: "ghostty", Name: "Ghostty", Description: "Terminal application and command-line candidates.", References: []string{"https://ghostty.org/docs/install/binary"}, SupportedScopes: []string{"user"}}, Discover: discoverGhostty, Checks: []CheckDefinition{{ID: "ghostty", Name: "Ghostty version", Question: "Is a supported update available?", Order: 3, Evaluate: checkGhosttyInstance}}},
		{Integration: Integration{ID: "starship", Name: "Starship", Description: "Shell prompt installations and update sources.", References: []string{"https://github.com/starship/starship"}, SupportedScopes: []string{"user"}}, Discover: discoverStarship, Checks: []CheckDefinition{{ID: "starship", Name: "Starship version", Question: "Is a supported update available?", Order: 4, Evaluate: checkStarshipInstance}}},
		{Integration: Integration{ID: "opencode", Name: "OpenCode", Description: "OpenCode installations and evidenced update sources.", References: []string{"https://github.com/anomalyco/opencode"}, SupportedScopes: []string{"user"}}, Discover: discoverOpenCode, Checks: []CheckDefinition{{ID: "opencode", Name: "OpenCode version", Question: "Is a supported update available?", Order: 5, Evaluate: checkOpenCodeInstance}}},
		{Integration: Integration{ID: "tokenjuice", Name: "Tokenjuice", Description: "Output compactor installations and evidenced update sources.", References: []string{"https://github.com/vincentkoc/tokenjuice"}, SupportedScopes: []string{"user"}}, Discover: discoverTokenjuice, Checks: []CheckDefinition{{ID: "tokenjuice", Name: "Tokenjuice version", Question: "Is a supported update available?", Order: 6, Evaluate: checkTokenjuiceInstance}}},
		{Integration: Integration{ID: "serena", Name: "Serena", Description: "Persistent tools and aggregate launch declarations.", References: []string{"https://github.com/oraios/serena"}, SupportedScopes: []string{"user"}}, Discover: discoverSerena, Checks: []CheckDefinition{{ID: "serena", Name: "Serena version", Question: "Is a supported update available?", Order: 7, Evaluate: checkSerenaInstance}}},
		{Integration: Integration{ID: "gortex", Name: "Gortex", Description: "Code graph installations and safe release inspection.", References: []string{"https://github.com/zzet/gortex"}, SupportedScopes: []string{"user"}}, Discover: discoverGortex, Checks: []CheckDefinition{{ID: "gortex", Name: "Gortex version", Question: "Is a supported update available?", Order: 8, Evaluate: checkGortexInstance}}},
		{Integration: Integration{ID: "brew", Name: "Homebrew", Description: "Selected prefix receipts with explicit freshness and coverage limits.", References: []string{"https://docs.brew.sh/Manpage"}, SupportedScopes: []string{"user"}}, Discover: discoverBrew, Checks: []CheckDefinition{{ID: "brew-outdated", Name: "Homebrew packages", Question: "Does the selected manager establish an update?", Order: 15, Evaluate: checkBrewInventory}}},
		{Integration: Integration{ID: "npm", Name: "npm global packages", Description: "Selected global package root, separate from project dependencies.", References: []string{"https://docs.npmjs.com/cli/v11/configuring-npm/folders"}, SupportedScopes: []string{"user"}}, Discover: discoverNpm, Checks: []CheckDefinition{{ID: "npm-outdated-g", Name: "Global npm packages", Question: "Are selected global packages up to date?", Order: 16, Evaluate: checkNpmGlobal}}},
	}
	configs := map[string][]CheckDefinition{
		"ghostty": {{ID: "ghostty-config-valid", Name: "Ghostty configuration syntax", Question: "Is configuration syntax supported?", Order: 9, Evaluate: checkGhosttyConfigValid}, {ID: "ghostty-config-version", Name: "Ghostty configuration compatibility", Question: "Is configuration compatible?", Order: 10, Evaluate: checkGhosttyConfigCompatibility}},
		"herdr":   {{ID: "herdr-config-valid", Name: "Herdr configuration syntax", Question: "Is configuration syntax supported?", Order: 11, Evaluate: checkHerdrConfigValid}, {ID: "herdr-config-version", Name: "Herdr configuration compatibility", Question: "Is configuration compatible?", Order: 12, Evaluate: checkHerdrConfigCompatibility}},
		"pi":      {{ID: "pi-config-valid", Name: "Pi configuration syntax", Question: "Is configuration syntax supported?", Order: 13, Evaluate: checkPiConfigValid}, {ID: "pi-config-version", Name: "Pi configuration compatibility", Question: "Is configuration compatible?", Order: 14, Evaluate: checkPiConfigCompatibility}},
	}
	for n := range defs {
		defs[n].Checks = append(defs[n].Checks, configs[defs[n].Integration.ID]...)
	}
	defs = append(defs,
		Definition{Integration: Integration{ID: "pi-packages", Name: "Pi packages", Description: "User and selected project package declarations.", References: []string{"https://github.com/earendil-works/pi"}, SupportedScopes: []string{"user", "project"}}, Discover: discoverPiPackages, Checks: []CheckDefinition{{ID: "pi-packages", Name: "Pi package sources", Question: "Does the declared source have an established update?", Order: 17, Evaluate: checkPiPackageSources}}},
		Definition{Integration: Integration{ID: "superpowers", Name: "Superpowers", Description: "Declared harness resources and explicit roots.", References: []string{"https://github.com/obra/superpowers"}, SupportedScopes: []string{"user", "project"}}, Discover: discoverSuperpowers, Checks: []CheckDefinition{{ID: "superpowers", Name: "Superpowers source intent", Question: "Does the requested source permit advancement?", Order: 18, Evaluate: checkSuperpowersSource}}},
		Definition{Integration: Integration{ID: "herdr-integr", Name: "Herdr integrations", Description: "Herdr integration state for discovered Pi and OpenCode targets.", References: []string{"https://github.com/herdrdev/herdr"}, SupportedScopes: []string{"user"}}, Discover: discoverHerdrIntegrations, Checks: []CheckDefinition{{ID: "herdr-integr", Name: "Herdr integration targets", Question: "Are supported Herdr targets current?", Order: 19, Evaluate: checkHerdrIntegrationTargets}}},
		Definition{Integration: Integration{ID: "herdr-plugins", Name: "Herdr plugins", Description: "Declared Herdr plugin sources from the current user's registry.", References: []string{"https://github.com/herdrdev/herdr"}, SupportedScopes: []string{"user"}}, Discover: discoverHerdrPlugins, Checks: []CheckDefinition{{ID: "herdr-plugins", Name: "Herdr plugin sources", Question: "Does each declared plugin have an established upstream change?", Order: 20, Evaluate: checkHerdrPluginSources}}},
	)
	return defs
}
